version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 5555:5555 # prisma studio
      # - 8000:8000
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: sh -c "npm run dev" # docker環境で開発を進めるなら必要

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # バインドする
    ports:
      - 5432:5432

volumes:
  postgres_data:
